#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_GameStateController

#include "Basic.hpp"

#include "E_DBDGameState_structs.hpp"


namespace SDK::Params
{

// Function BPI_GameStateController.BPI_GameStateController_C.OnGameStateObtained
// 0x0001 (0x0001 - 0x0000)
struct BPI_GameStateController_C_OnGameStateObtained final
{
public:
	E_DBDGameState                                DBDGameState;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPI_GameStateController_C_OnGameStateObtained) == 0x000001, "Wrong alignment on BPI_GameStateController_C_OnGameStateObtained");
static_assert(sizeof(BPI_GameStateController_C_OnGameStateObtained) == 0x000001, "Wrong size on BPI_GameStateController_C_OnGameStateObtained");
static_assert(offsetof(BPI_GameStateController_C_OnGameStateObtained, DBDGameState) == 0x000000, "Member 'BPI_GameStateController_C_OnGameStateObtained::DBDGameState' has a wrong offset!");

}

