#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RetentionRewardsUtilities

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class RetentionRewardsUtilities.RetentionRewardsSubsystem
// 0x0148 (0x0180 - 0x0038)
class URetentionRewardsSubsystem final : public UGameInstanceSubsystem
{
public:
	uint8                                         Pad_38[0x148];                                     // 0x0038(0x0148)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"RetentionRewardsSubsystem">();
	}
	static class URetentionRewardsSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<URetentionRewardsSubsystem>();
	}
};
static_assert(alignof(URetentionRewardsSubsystem) == 0x000008, "Wrong alignment on URetentionRewardsSubsystem");
static_assert(sizeof(URetentionRewardsSubsystem) == 0x000180, "Wrong size on URetentionRewardsSubsystem");

}

