#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SkillCheckProbabilityProficiency

#include "Basic.hpp"

#include "SkillCheckProbabilityProficiency_classes.hpp"
#include "SkillCheckProbabilityProficiency_parameters.hpp"


namespace SDK
{

// Function SkillCheckProbabilityProficiency.SkillCheckProbabilityProficiency_C.GetValue
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const class UChargeableInteractionDefinition*chargeableInteraction                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class ADBDPlayer*                 player                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float USkillCheckProbabilityProficiency_C::GetValue(const class UChargeableInteractionDefinition* chargeableInteraction, const class ADBDPlayer* player) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SkillCheckProbabilityProficiency_C", "GetValue");

	Params::SkillCheckProbabilityProficiency_C_GetValue Parms{};

	Parms.chargeableInteraction = chargeableInteraction;
	Parms.player = player;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SkillCheckProbabilityProficiency.SkillCheckProbabilityProficiency_C.GetType
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const float                             value                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EStatusEffectType                       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

EStatusEffectType USkillCheckProbabilityProficiency_C::GetType(const float value) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SkillCheckProbabilityProficiency_C", "GetType");

	Params::SkillCheckProbabilityProficiency_C_GetType Parms{};

	Parms.value = value;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SkillCheckProbabilityProficiency.SkillCheckProbabilityProficiency_C.GetIsActive
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const class UChargeableInteractionDefinition*chargeableInteraction                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class ADBDPlayer*                 player                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool USkillCheckProbabilityProficiency_C::GetIsActive(const class UChargeableInteractionDefinition* chargeableInteraction, const class ADBDPlayer* player) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SkillCheckProbabilityProficiency_C", "GetIsActive");

	Params::SkillCheckProbabilityProficiency_C_GetIsActive Parms{};

	Parms.chargeableInteraction = chargeableInteraction;
	Parms.player = player;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

