#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TheHillbilly

#include "Basic.hpp"

#include "TheHillbilly_classes.hpp"
#include "TheHillbilly_parameters.hpp"


namespace SDK
{

// Function TheHillbilly.ChainsawRevInteraction.OnLevelReadyToPlay
// (Final, Native, Private)

void UChainsawRevInteraction::OnLevelReadyToPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ChainsawRevInteraction", "OnLevelReadyToPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function TheHillbilly.HillbillyChainsawOverheatComponent.Authority_OnHeatChargeEmpty
// (Final, Native, Private)

void UHillbillyChainsawOverheatComponent::Authority_OnHeatChargeEmpty()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HillbillyChainsawOverheatComponent", "Authority_OnHeatChargeEmpty");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function TheHillbilly.HillbillyChainsawOverheatComponent.Authority_OnHeatChargeFull
// (Final, Native, Private)

void UHillbillyChainsawOverheatComponent::Authority_OnHeatChargeFull()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HillbillyChainsawOverheatComponent", "Authority_OnHeatChargeFull");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function TheHillbilly.HillbillyChainsawOverheatComponent.OnHeatChargeUpdate
// (Final, Native, Private)
// Parameters:
// const float                             currentCharge                                          (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             previosCharge                                          (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UHillbillyChainsawOverheatComponent::OnHeatChargeUpdate(const float currentCharge, const float previosCharge)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HillbillyChainsawOverheatComponent", "OnHeatChargeUpdate");

	Params::HillbillyChainsawOverheatComponent_OnHeatChargeUpdate Parms{};

	Parms.currentCharge = currentCharge;
	Parms.previosCharge = previosCharge;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function TheHillbilly.HillbillyChainsawOverheatComponent.OnLevelReadyToPlay
// (Final, Native, Private)

void UHillbillyChainsawOverheatComponent::OnLevelReadyToPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HillbillyChainsawOverheatComponent", "OnLevelReadyToPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function TheHillbilly.HillbillyChainsawOverheatComponent.OnRep_IsChainsawOverheating
// (Final, Native, Private)

void UHillbillyChainsawOverheatComponent::OnRep_IsChainsawOverheating()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HillbillyChainsawOverheatComponent", "OnRep_IsChainsawOverheating");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function TheHillbilly.HillbillyChainsawOverheatComponent.IsChainsawOverheating
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UHillbillyChainsawOverheatComponent::IsChainsawOverheating() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HillbillyChainsawOverheatComponent", "IsChainsawOverheating");

	Params::HillbillyChainsawOverheatComponent_IsChainsawOverheating Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function TheHillbilly.HillbillyOverheatPresentationItemProgressComponent.SetHillbillyChainsawOverheatComponent
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UHillbillyChainsawOverheatComponent*hillbillyChainsawOverheatComponent                     (Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UHillbillyOverheatPresentationItemProgressComponent::SetHillbillyChainsawOverheatComponent(class UHillbillyChainsawOverheatComponent* hillbillyChainsawOverheatComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HillbillyOverheatPresentationItemProgressComponent", "SetHillbillyChainsawOverheatComponent");

	Params::HillbillyOverheatPresentationItemProgressComponent_SetHillbillyChainsawOverheatComponent Parms{};

	Parms.hillbillyChainsawOverheatComponent = hillbillyChainsawOverheatComponent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

