#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DebugStats

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function WBP_DebugStats.WBP_DebugStats_C.ExecuteUbergraph_WBP_DebugStats
// 0x00F0 (0x00F0 - 0x0000)
struct WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_Actor_Reference;                      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_Event_Hit_Location;                         // 0x0010(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      K2Node_Event_Original_PC;                          // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_Event_Restored_PC;                          // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEngineVersion_ReturnValue;             // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_CustomEvent_Actor_Reference;                // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_CustomEvent_Hit_Location;                   // 0x0048(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_StartsWith_ReturnValue;                   // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0068(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_CustomEvent_Text_To_Set;                    // 0x0088(0x0018)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x00A0(0x0014)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x00B8(0x0008)(NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_PlayerLocation_ReturnValue;       // 0x00C0(0x0018)()
	class FText                                   CallFunc_GetText_PlayerRotation_ReturnValue;       // 0x00D8(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats) == 0x000008, "Wrong alignment on WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats");
static_assert(sizeof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats) == 0x0000F0, "Wrong size on WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, EntryPoint) == 0x000000, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, K2Node_Event_Actor_Reference) == 0x000008, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::K2Node_Event_Actor_Reference' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, K2Node_Event_Hit_Location) == 0x000010, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::K2Node_Event_Hit_Location' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, K2Node_Event_Original_PC) == 0x000020, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::K2Node_Event_Original_PC' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, K2Node_Event_Restored_PC) == 0x000028, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::K2Node_Event_Restored_PC' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, CallFunc_GetEngineVersion_ReturnValue) == 0x000030, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::CallFunc_GetEngineVersion_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, K2Node_CustomEvent_Actor_Reference) == 0x000040, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::K2Node_CustomEvent_Actor_Reference' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, K2Node_CustomEvent_Hit_Location) == 0x000048, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::K2Node_CustomEvent_Hit_Location' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, CallFunc_StartsWith_ReturnValue) == 0x000054, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::CallFunc_StartsWith_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, CallFunc_GetDisplayName_ReturnValue) == 0x000058, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, CallFunc_Conv_StringToText_ReturnValue) == 0x000068, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, CallFunc_IsValid_ReturnValue) == 0x000080, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, K2Node_CustomEvent_Text_To_Set) == 0x000088, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::K2Node_CustomEvent_Text_To_Set' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, K2Node_CreateDelegate_OutputDelegate) == 0x0000A0, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x0000B8, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, CallFunc_GetText_PlayerLocation_ReturnValue) == 0x0000C0, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::CallFunc_GetText_PlayerLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats, CallFunc_GetText_PlayerRotation_ReturnValue) == 0x0000D8, "Member 'WBP_DebugStats_C_ExecuteUbergraph_WBP_DebugStats::CallFunc_GetText_PlayerRotation_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.Event Set Looking At Actor
// 0x0018 (0x0018 - 0x0000)
struct WBP_DebugStats_C_Event_Set_Looking_At_Actor final
{
public:
	class FText                                   Text_To_Set;                                       // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_DebugStats_C_Event_Set_Looking_At_Actor) == 0x000008, "Wrong alignment on WBP_DebugStats_C_Event_Set_Looking_At_Actor");
static_assert(sizeof(WBP_DebugStats_C_Event_Set_Looking_At_Actor) == 0x000018, "Wrong size on WBP_DebugStats_C_Event_Set_Looking_At_Actor");
static_assert(offsetof(WBP_DebugStats_C_Event_Set_Looking_At_Actor, Text_To_Set) == 0x000000, "Member 'WBP_DebugStats_C_Event_Set_Looking_At_Actor::Text_To_Set' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.Event Update Looking At Actor
// 0x0018 (0x0018 - 0x0000)
struct WBP_DebugStats_C_Event_Update_Looking_At_Actor final
{
public:
	class AActor*                                 Actor_Reference;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Hit_Location;                                      // 0x0008(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_DebugStats_C_Event_Update_Looking_At_Actor) == 0x000008, "Wrong alignment on WBP_DebugStats_C_Event_Update_Looking_At_Actor");
static_assert(sizeof(WBP_DebugStats_C_Event_Update_Looking_At_Actor) == 0x000018, "Wrong size on WBP_DebugStats_C_Event_Update_Looking_At_Actor");
static_assert(offsetof(WBP_DebugStats_C_Event_Update_Looking_At_Actor, Actor_Reference) == 0x000000, "Member 'WBP_DebugStats_C_Event_Update_Looking_At_Actor::Actor_Reference' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_Event_Update_Looking_At_Actor, Hit_Location) == 0x000008, "Member 'WBP_DebugStats_C_Event_Update_Looking_At_Actor::Hit_Location' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.On Debug Camera Deactivate
// 0x0008 (0x0008 - 0x0000)
struct WBP_DebugStats_C_On_Debug_Camera_Deactivate final
{
public:
	class APlayerController*                      Restored_PC;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_DebugStats_C_On_Debug_Camera_Deactivate) == 0x000008, "Wrong alignment on WBP_DebugStats_C_On_Debug_Camera_Deactivate");
static_assert(sizeof(WBP_DebugStats_C_On_Debug_Camera_Deactivate) == 0x000008, "Wrong size on WBP_DebugStats_C_On_Debug_Camera_Deactivate");
static_assert(offsetof(WBP_DebugStats_C_On_Debug_Camera_Deactivate, Restored_PC) == 0x000000, "Member 'WBP_DebugStats_C_On_Debug_Camera_Deactivate::Restored_PC' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.On Debug Camera Activate
// 0x0008 (0x0008 - 0x0000)
struct WBP_DebugStats_C_On_Debug_Camera_Activate final
{
public:
	class APlayerController*                      Original_PC;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_DebugStats_C_On_Debug_Camera_Activate) == 0x000008, "Wrong alignment on WBP_DebugStats_C_On_Debug_Camera_Activate");
static_assert(sizeof(WBP_DebugStats_C_On_Debug_Camera_Activate) == 0x000008, "Wrong size on WBP_DebugStats_C_On_Debug_Camera_Activate");
static_assert(offsetof(WBP_DebugStats_C_On_Debug_Camera_Activate, Original_PC) == 0x000000, "Member 'WBP_DebugStats_C_On_Debug_Camera_Activate::Original_PC' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.On Debug Camera Actor Selected
// 0x0018 (0x0018 - 0x0000)
struct WBP_DebugStats_C_On_Debug_Camera_Actor_Selected final
{
public:
	class AActor*                                 Actor_Reference;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Hit_Location;                                      // 0x0008(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_DebugStats_C_On_Debug_Camera_Actor_Selected) == 0x000008, "Wrong alignment on WBP_DebugStats_C_On_Debug_Camera_Actor_Selected");
static_assert(sizeof(WBP_DebugStats_C_On_Debug_Camera_Actor_Selected) == 0x000018, "Wrong size on WBP_DebugStats_C_On_Debug_Camera_Actor_Selected");
static_assert(offsetof(WBP_DebugStats_C_On_Debug_Camera_Actor_Selected, Actor_Reference) == 0x000000, "Member 'WBP_DebugStats_C_On_Debug_Camera_Actor_Selected::Actor_Reference' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_On_Debug_Camera_Actor_Selected, Hit_Location) == 0x000008, "Member 'WBP_DebugStats_C_On_Debug_Camera_Actor_Selected::Hit_Location' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_Console
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_DebugStats_C_GetText_Console final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class UObject*                                CallFunc_Get_Console_Console_Reference;            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0020(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0038(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0078(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0088(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_Console) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_Console");
static_assert(sizeof(WBP_DebugStats_C_GetText_Console) == 0x0000A0, "Wrong size on WBP_DebugStats_C_GetText_Console");
static_assert(offsetof(WBP_DebugStats_C_GetText_Console, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_Console::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_Console, CallFunc_Get_Console_Console_Reference) == 0x000018, "Member 'WBP_DebugStats_C_GetText_Console::CallFunc_Get_Console_Console_Reference' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_Console, CallFunc_Conv_ObjectToText_ReturnValue) == 0x000020, "Member 'WBP_DebugStats_C_GetText_Console::CallFunc_Conv_ObjectToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_Console, K2Node_MakeStruct_FormatArgumentData) == 0x000038, "Member 'WBP_DebugStats_C_GetText_Console::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_Console, K2Node_MakeArray_Array) == 0x000078, "Member 'WBP_DebugStats_C_GetText_Console::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_Console, CallFunc_Format_ReturnValue) == 0x000088, "Member 'WBP_DebugStats_C_GetText_Console::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_CheatManager
// 0x00A8 (0x00A8 - 0x0000)
struct WBP_DebugStats_C_GetText_CheatManager final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCheatManager*                          CallFunc_Get_CheatManager_Cheat_Manager_Reference; // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0028(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0040(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0080(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0090(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_CheatManager) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_CheatManager");
static_assert(sizeof(WBP_DebugStats_C_GetText_CheatManager) == 0x0000A8, "Wrong size on WBP_DebugStats_C_GetText_CheatManager");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManager, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_CheatManager::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManager, CallFunc_GetPlayerController_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_CheatManager::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManager, CallFunc_Get_CheatManager_Cheat_Manager_Reference) == 0x000020, "Member 'WBP_DebugStats_C_GetText_CheatManager::CallFunc_Get_CheatManager_Cheat_Manager_Reference' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManager, CallFunc_Conv_ObjectToText_ReturnValue) == 0x000028, "Member 'WBP_DebugStats_C_GetText_CheatManager::CallFunc_Conv_ObjectToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManager, K2Node_MakeStruct_FormatArgumentData) == 0x000040, "Member 'WBP_DebugStats_C_GetText_CheatManager::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManager, K2Node_MakeArray_Array) == 0x000080, "Member 'WBP_DebugStats_C_GetText_CheatManager::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManager, CallFunc_Format_ReturnValue) == 0x000090, "Member 'WBP_DebugStats_C_GetText_CheatManager::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_CheatManagerClass
// 0x00B8 (0x00B8 - 0x0000)
struct WBP_DebugStats_C_GetText_CheatManagerClass final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_Get_CheatManagerClass_Cheat_Manager_Class; // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetClassDisplayName_ReturnValue;          // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0038(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0050(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0090(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00A0(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_CheatManagerClass) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_CheatManagerClass");
static_assert(sizeof(WBP_DebugStats_C_GetText_CheatManagerClass) == 0x0000B8, "Wrong size on WBP_DebugStats_C_GetText_CheatManagerClass");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManagerClass, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_CheatManagerClass::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManagerClass, CallFunc_GetPlayerController_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_CheatManagerClass::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManagerClass, CallFunc_Get_CheatManagerClass_Cheat_Manager_Class) == 0x000020, "Member 'WBP_DebugStats_C_GetText_CheatManagerClass::CallFunc_Get_CheatManagerClass_Cheat_Manager_Class' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManagerClass, CallFunc_GetClassDisplayName_ReturnValue) == 0x000028, "Member 'WBP_DebugStats_C_GetText_CheatManagerClass::CallFunc_GetClassDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManagerClass, CallFunc_Conv_StringToText_ReturnValue) == 0x000038, "Member 'WBP_DebugStats_C_GetText_CheatManagerClass::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManagerClass, K2Node_MakeStruct_FormatArgumentData) == 0x000050, "Member 'WBP_DebugStats_C_GetText_CheatManagerClass::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManagerClass, K2Node_MakeArray_Array) == 0x000090, "Member 'WBP_DebugStats_C_GetText_CheatManagerClass::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CheatManagerClass, CallFunc_Format_ReturnValue) == 0x0000A0, "Member 'WBP_DebugStats_C_GetText_CheatManagerClass::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_PlayerController
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_DebugStats_C_GetText_PlayerController final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0020(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0038(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0078(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0088(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_PlayerController) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_PlayerController");
static_assert(sizeof(WBP_DebugStats_C_GetText_PlayerController) == 0x0000A0, "Wrong size on WBP_DebugStats_C_GetText_PlayerController");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerController, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_PlayerController::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerController, CallFunc_GetPlayerController_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_PlayerController::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerController, CallFunc_Conv_ObjectToText_ReturnValue) == 0x000020, "Member 'WBP_DebugStats_C_GetText_PlayerController::CallFunc_Conv_ObjectToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerController, K2Node_MakeStruct_FormatArgumentData) == 0x000038, "Member 'WBP_DebugStats_C_GetText_PlayerController::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerController, K2Node_MakeArray_Array) == 0x000078, "Member 'WBP_DebugStats_C_GetText_PlayerController::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerController, CallFunc_Format_ReturnValue) == 0x000088, "Member 'WBP_DebugStats_C_GetText_PlayerController::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_AcknowledgedPawn
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_DebugStats_C_GetText_AcknowledgedPawn final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0020(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0038(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0078(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0088(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_AcknowledgedPawn) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_AcknowledgedPawn");
static_assert(sizeof(WBP_DebugStats_C_GetText_AcknowledgedPawn) == 0x0000A0, "Wrong size on WBP_DebugStats_C_GetText_AcknowledgedPawn");
static_assert(offsetof(WBP_DebugStats_C_GetText_AcknowledgedPawn, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_AcknowledgedPawn::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_AcknowledgedPawn, CallFunc_GetPlayerController_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_AcknowledgedPawn::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_AcknowledgedPawn, CallFunc_Conv_ObjectToText_ReturnValue) == 0x000020, "Member 'WBP_DebugStats_C_GetText_AcknowledgedPawn::CallFunc_Conv_ObjectToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_AcknowledgedPawn, K2Node_MakeStruct_FormatArgumentData) == 0x000038, "Member 'WBP_DebugStats_C_GetText_AcknowledgedPawn::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_AcknowledgedPawn, K2Node_MakeArray_Array) == 0x000078, "Member 'WBP_DebugStats_C_GetText_AcknowledgedPawn::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_AcknowledgedPawn, CallFunc_Format_ReturnValue) == 0x000088, "Member 'WBP_DebugStats_C_GetText_AcknowledgedPawn::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_PlayerLocation
// 0x0170 (0x0170 - 0x0000)
struct WBP_DebugStats_C_GetText_PlayerLocation final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakVector_X;                            // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue; // 0x0040(0x0018)()
	class FText                                   CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_1; // 0x0058(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0070(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x00B0(0x0040)(HasGetValueTypeHash)
	class FText                                   CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_2; // 0x00F0(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x0108(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0148(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0158(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_PlayerLocation) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_PlayerLocation");
static_assert(sizeof(WBP_DebugStats_C_GetText_PlayerLocation) == 0x000170, "Wrong size on WBP_DebugStats_C_GetText_PlayerLocation");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, CallFunc_GetPlayerPawn_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000020, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, CallFunc_IsValid_ReturnValue) == 0x00002C, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, CallFunc_BreakVector_X) == 0x000030, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, CallFunc_BreakVector_Y) == 0x000034, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, CallFunc_BreakVector_Z) == 0x000038, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue) == 0x000040, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_1) == 0x000058, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, K2Node_MakeStruct_FormatArgumentData) == 0x000070, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, K2Node_MakeStruct_FormatArgumentData_1) == 0x0000B0, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_2) == 0x0000F0, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, K2Node_MakeStruct_FormatArgumentData_2) == 0x000108, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, K2Node_MakeArray_Array) == 0x000148, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerLocation, CallFunc_Format_ReturnValue) == 0x000158, "Member 'WBP_DebugStats_C_GetText_PlayerLocation::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_PlayerRotation
// 0x0170 (0x0170 - 0x0000)
struct WBP_DebugStats_C_GetText_PlayerRotation final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakRotator_Roll;                        // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue; // 0x0040(0x0018)()
	class FText                                   CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_1; // 0x0058(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0070(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x00B0(0x0040)(HasGetValueTypeHash)
	class FText                                   CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_2; // 0x00F0(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x0108(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0148(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0158(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_PlayerRotation) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_PlayerRotation");
static_assert(sizeof(WBP_DebugStats_C_GetText_PlayerRotation) == 0x000170, "Wrong size on WBP_DebugStats_C_GetText_PlayerRotation");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, CallFunc_GetPlayerPawn_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, CallFunc_K2_GetActorRotation_ReturnValue) == 0x000020, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::CallFunc_K2_GetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, CallFunc_IsValid_ReturnValue) == 0x00002C, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, CallFunc_BreakRotator_Roll) == 0x000030, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, CallFunc_BreakRotator_Pitch) == 0x000034, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, CallFunc_BreakRotator_Yaw) == 0x000038, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue) == 0x000040, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_1) == 0x000058, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, K2Node_MakeStruct_FormatArgumentData) == 0x000070, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, K2Node_MakeStruct_FormatArgumentData_1) == 0x0000B0, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_2) == 0x0000F0, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::CallFunc_GetRichText_FormatPositiveNegativeValue_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, K2Node_MakeStruct_FormatArgumentData_2) == 0x000108, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, K2Node_MakeArray_Array) == 0x000148, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_PlayerRotation, CallFunc_Format_ReturnValue) == 0x000158, "Member 'WBP_DebugStats_C_GetText_PlayerRotation::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_LocalPlayer
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_DebugStats_C_GetText_LocalPlayer final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0020(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0038(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0078(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0088(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_LocalPlayer) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_LocalPlayer");
static_assert(sizeof(WBP_DebugStats_C_GetText_LocalPlayer) == 0x0000A0, "Wrong size on WBP_DebugStats_C_GetText_LocalPlayer");
static_assert(offsetof(WBP_DebugStats_C_GetText_LocalPlayer, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_LocalPlayer::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_LocalPlayer, CallFunc_GetPlayerController_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_LocalPlayer::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_LocalPlayer, CallFunc_Conv_ObjectToText_ReturnValue) == 0x000020, "Member 'WBP_DebugStats_C_GetText_LocalPlayer::CallFunc_Conv_ObjectToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_LocalPlayer, K2Node_MakeStruct_FormatArgumentData) == 0x000038, "Member 'WBP_DebugStats_C_GetText_LocalPlayer::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_LocalPlayer, K2Node_MakeArray_Array) == 0x000078, "Member 'WBP_DebugStats_C_GetText_LocalPlayer::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_LocalPlayer, CallFunc_Format_ReturnValue) == 0x000088, "Member 'WBP_DebugStats_C_GetText_LocalPlayer::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_MovementComponent
// 0x00A8 (0x00A8 - 0x0000)
struct WBP_DebugStats_C_GetText_MovementComponent final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPawnMovementComponent*                 CallFunc_GetMovementComponent_ReturnValue;         // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0028(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0040(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0080(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0090(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_MovementComponent) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_MovementComponent");
static_assert(sizeof(WBP_DebugStats_C_GetText_MovementComponent) == 0x0000A8, "Wrong size on WBP_DebugStats_C_GetText_MovementComponent");
static_assert(offsetof(WBP_DebugStats_C_GetText_MovementComponent, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_MovementComponent::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_MovementComponent, CallFunc_GetPlayerPawn_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_MovementComponent::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_MovementComponent, CallFunc_GetMovementComponent_ReturnValue) == 0x000020, "Member 'WBP_DebugStats_C_GetText_MovementComponent::CallFunc_GetMovementComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_MovementComponent, CallFunc_Conv_ObjectToText_ReturnValue) == 0x000028, "Member 'WBP_DebugStats_C_GetText_MovementComponent::CallFunc_Conv_ObjectToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_MovementComponent, K2Node_MakeStruct_FormatArgumentData) == 0x000040, "Member 'WBP_DebugStats_C_GetText_MovementComponent::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_MovementComponent, K2Node_MakeArray_Array) == 0x000080, "Member 'WBP_DebugStats_C_GetText_MovementComponent::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_MovementComponent, CallFunc_Format_ReturnValue) == 0x000090, "Member 'WBP_DebugStats_C_GetText_MovementComponent::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_CameraManager
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_DebugStats_C_GetText_CameraManager final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class APlayerCameraManager*                   CallFunc_GetPlayerCameraManager_ReturnValue;       // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0020(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0038(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0078(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0088(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_CameraManager) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_CameraManager");
static_assert(sizeof(WBP_DebugStats_C_GetText_CameraManager) == 0x0000A0, "Wrong size on WBP_DebugStats_C_GetText_CameraManager");
static_assert(offsetof(WBP_DebugStats_C_GetText_CameraManager, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_CameraManager::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CameraManager, CallFunc_GetPlayerCameraManager_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_CameraManager::CallFunc_GetPlayerCameraManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CameraManager, CallFunc_Conv_ObjectToText_ReturnValue) == 0x000020, "Member 'WBP_DebugStats_C_GetText_CameraManager::CallFunc_Conv_ObjectToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CameraManager, K2Node_MakeStruct_FormatArgumentData) == 0x000038, "Member 'WBP_DebugStats_C_GetText_CameraManager::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CameraManager, K2Node_MakeArray_Array) == 0x000078, "Member 'WBP_DebugStats_C_GetText_CameraManager::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CameraManager, CallFunc_Format_ReturnValue) == 0x000088, "Member 'WBP_DebugStats_C_GetText_CameraManager::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_ViewportClient
// 0x00B0 (0x00B0 - 0x0000)
struct WBP_DebugStats_C_GetText_ViewportClient final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULocalPlayer*                           K2Node_DynamicCast_AsLocal_Player;                 // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0030(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0048(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0088(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0098(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_ViewportClient) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_ViewportClient");
static_assert(sizeof(WBP_DebugStats_C_GetText_ViewportClient) == 0x0000B0, "Wrong size on WBP_DebugStats_C_GetText_ViewportClient");
static_assert(offsetof(WBP_DebugStats_C_GetText_ViewportClient, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_ViewportClient::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_ViewportClient, CallFunc_GetPlayerController_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_ViewportClient::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_ViewportClient, K2Node_DynamicCast_AsLocal_Player) == 0x000020, "Member 'WBP_DebugStats_C_GetText_ViewportClient::K2Node_DynamicCast_AsLocal_Player' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_ViewportClient, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'WBP_DebugStats_C_GetText_ViewportClient::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_ViewportClient, CallFunc_Conv_ObjectToText_ReturnValue) == 0x000030, "Member 'WBP_DebugStats_C_GetText_ViewportClient::CallFunc_Conv_ObjectToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_ViewportClient, K2Node_MakeStruct_FormatArgumentData) == 0x000048, "Member 'WBP_DebugStats_C_GetText_ViewportClient::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_ViewportClient, K2Node_MakeArray_Array) == 0x000088, "Member 'WBP_DebugStats_C_GetText_ViewportClient::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_ViewportClient, CallFunc_Format_ReturnValue) == 0x000098, "Member 'WBP_DebugStats_C_GetText_ViewportClient::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_GameInstance
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_DebugStats_C_GetText_GameInstance final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0020(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0038(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0078(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0088(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_GameInstance) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_GameInstance");
static_assert(sizeof(WBP_DebugStats_C_GetText_GameInstance) == 0x0000A0, "Wrong size on WBP_DebugStats_C_GetText_GameInstance");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameInstance, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_GameInstance::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameInstance, CallFunc_GetGameInstance_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_GameInstance::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameInstance, CallFunc_Conv_ObjectToText_ReturnValue) == 0x000020, "Member 'WBP_DebugStats_C_GetText_GameInstance::CallFunc_Conv_ObjectToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameInstance, K2Node_MakeStruct_FormatArgumentData) == 0x000038, "Member 'WBP_DebugStats_C_GetText_GameInstance::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameInstance, K2Node_MakeArray_Array) == 0x000078, "Member 'WBP_DebugStats_C_GetText_GameInstance::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameInstance, CallFunc_Format_ReturnValue) == 0x000088, "Member 'WBP_DebugStats_C_GetText_GameInstance::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_GameMode
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_DebugStats_C_GetText_GameMode final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class AGameModeBase*                          CallFunc_GetGameMode_ReturnValue;                  // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0020(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0038(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0078(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0088(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_GameMode) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_GameMode");
static_assert(sizeof(WBP_DebugStats_C_GetText_GameMode) == 0x0000A0, "Wrong size on WBP_DebugStats_C_GetText_GameMode");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameMode, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_GameMode::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameMode, CallFunc_GetGameMode_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_GameMode::CallFunc_GetGameMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameMode, CallFunc_Conv_ObjectToText_ReturnValue) == 0x000020, "Member 'WBP_DebugStats_C_GetText_GameMode::CallFunc_Conv_ObjectToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameMode, K2Node_MakeStruct_FormatArgumentData) == 0x000038, "Member 'WBP_DebugStats_C_GetText_GameMode::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameMode, K2Node_MakeArray_Array) == 0x000078, "Member 'WBP_DebugStats_C_GetText_GameMode::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameMode, CallFunc_Format_ReturnValue) == 0x000088, "Member 'WBP_DebugStats_C_GetText_GameMode::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_GameState
// 0x00A0 (0x00A0 - 0x0000)
struct WBP_DebugStats_C_GetText_GameState final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0020(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0038(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0078(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0088(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_GameState) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_GameState");
static_assert(sizeof(WBP_DebugStats_C_GetText_GameState) == 0x0000A0, "Wrong size on WBP_DebugStats_C_GetText_GameState");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameState, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_GameState::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameState, CallFunc_GetGameState_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_GameState::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameState, CallFunc_Conv_ObjectToText_ReturnValue) == 0x000020, "Member 'WBP_DebugStats_C_GetText_GameState::CallFunc_Conv_ObjectToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameState, K2Node_MakeStruct_FormatArgumentData) == 0x000038, "Member 'WBP_DebugStats_C_GetText_GameState::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameState, K2Node_MakeArray_Array) == 0x000078, "Member 'WBP_DebugStats_C_GetText_GameState::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameState, CallFunc_Format_ReturnValue) == 0x000088, "Member 'WBP_DebugStats_C_GetText_GameState::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_CommandLine
// 0x00F8 (0x00F8 - 0x0000)
struct WBP_DebugStats_C_GetText_CommandLine final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          Temp_bool_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0020(0x0010)(ReferenceParm)
	class FString                                 CallFunc_GetCommandLine_ReturnValue;               // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0040(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0058(0x0018)()
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0078(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x00B8(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x00C8(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x00E0(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_CommandLine) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_CommandLine");
static_assert(sizeof(WBP_DebugStats_C_GetText_CommandLine) == 0x0000F8, "Wrong size on WBP_DebugStats_C_GetText_CommandLine");
static_assert(offsetof(WBP_DebugStats_C_GetText_CommandLine, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_CommandLine::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CommandLine, Temp_bool_Variable) == 0x000018, "Member 'WBP_DebugStats_C_GetText_CommandLine::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CommandLine, K2Node_MakeArray_Array) == 0x000020, "Member 'WBP_DebugStats_C_GetText_CommandLine::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CommandLine, CallFunc_GetCommandLine_ReturnValue) == 0x000030, "Member 'WBP_DebugStats_C_GetText_CommandLine::CallFunc_GetCommandLine_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CommandLine, CallFunc_Format_ReturnValue) == 0x000040, "Member 'WBP_DebugStats_C_GetText_CommandLine::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CommandLine, CallFunc_Conv_StringToText_ReturnValue) == 0x000058, "Member 'WBP_DebugStats_C_GetText_CommandLine::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CommandLine, CallFunc_IsEmpty_ReturnValue) == 0x000070, "Member 'WBP_DebugStats_C_GetText_CommandLine::CallFunc_IsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CommandLine, K2Node_MakeStruct_FormatArgumentData) == 0x000078, "Member 'WBP_DebugStats_C_GetText_CommandLine::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CommandLine, K2Node_MakeArray_Array_1) == 0x0000B8, "Member 'WBP_DebugStats_C_GetText_CommandLine::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CommandLine, CallFunc_Format_ReturnValue_1) == 0x0000C8, "Member 'WBP_DebugStats_C_GetText_CommandLine::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CommandLine, K2Node_Select_Default) == 0x0000E0, "Member 'WBP_DebugStats_C_GetText_CommandLine::K2Node_Select_Default' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_GameName
// 0x00A8 (0x00A8 - 0x0000)
struct WBP_DebugStats_C_GetText_GameName final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FString                                 CallFunc_GetGameName_ReturnValue;                  // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0028(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0040(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0080(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0090(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_GameName) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_GameName");
static_assert(sizeof(WBP_DebugStats_C_GetText_GameName) == 0x0000A8, "Wrong size on WBP_DebugStats_C_GetText_GameName");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameName, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_GameName::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameName, CallFunc_GetGameName_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_GameName::CallFunc_GetGameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameName, CallFunc_Conv_StringToText_ReturnValue) == 0x000028, "Member 'WBP_DebugStats_C_GetText_GameName::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameName, K2Node_MakeStruct_FormatArgumentData) == 0x000040, "Member 'WBP_DebugStats_C_GetText_GameName::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameName, K2Node_MakeArray_Array) == 0x000080, "Member 'WBP_DebugStats_C_GetText_GameName::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GameName, CallFunc_Format_ReturnValue) == 0x000090, "Member 'WBP_DebugStats_C_GetText_GameName::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_GamePlatform
// 0x00A8 (0x00A8 - 0x0000)
struct WBP_DebugStats_C_GetText_GamePlatform final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FString                                 CallFunc_GetPlatformName_ReturnValue;              // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0028(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0040(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0080(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0090(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_GamePlatform) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_GamePlatform");
static_assert(sizeof(WBP_DebugStats_C_GetText_GamePlatform) == 0x0000A8, "Wrong size on WBP_DebugStats_C_GetText_GamePlatform");
static_assert(offsetof(WBP_DebugStats_C_GetText_GamePlatform, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_GamePlatform::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GamePlatform, CallFunc_GetPlatformName_ReturnValue) == 0x000018, "Member 'WBP_DebugStats_C_GetText_GamePlatform::CallFunc_GetPlatformName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GamePlatform, CallFunc_Conv_StringToText_ReturnValue) == 0x000028, "Member 'WBP_DebugStats_C_GetText_GamePlatform::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GamePlatform, K2Node_MakeStruct_FormatArgumentData) == 0x000040, "Member 'WBP_DebugStats_C_GetText_GamePlatform::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GamePlatform, K2Node_MakeArray_Array) == 0x000080, "Member 'WBP_DebugStats_C_GetText_GamePlatform::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_GamePlatform, CallFunc_Format_ReturnValue) == 0x000090, "Member 'WBP_DebugStats_C_GetText_GamePlatform::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetText_CurrentTime
// 0x0178 (0x0178 - 0x0000)
struct WBP_DebugStats_C_GetText_CurrentTime final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class FString                                 CallFunc_GetCurrentTime_Hour;                      // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetCurrentTime_Minute;                    // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetCurrentTime_Second;                    // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0048(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0060(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0078(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x00B8(0x0040)(HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x00F8(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x0110(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0150(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0160(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetText_CurrentTime) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetText_CurrentTime");
static_assert(sizeof(WBP_DebugStats_C_GetText_CurrentTime) == 0x000178, "Wrong size on WBP_DebugStats_C_GetText_CurrentTime");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, ReturnValue) == 0x000000, "Member 'WBP_DebugStats_C_GetText_CurrentTime::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, CallFunc_GetCurrentTime_Hour) == 0x000018, "Member 'WBP_DebugStats_C_GetText_CurrentTime::CallFunc_GetCurrentTime_Hour' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, CallFunc_GetCurrentTime_Minute) == 0x000028, "Member 'WBP_DebugStats_C_GetText_CurrentTime::CallFunc_GetCurrentTime_Minute' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, CallFunc_GetCurrentTime_Second) == 0x000038, "Member 'WBP_DebugStats_C_GetText_CurrentTime::CallFunc_GetCurrentTime_Second' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, CallFunc_Conv_StringToText_ReturnValue) == 0x000048, "Member 'WBP_DebugStats_C_GetText_CurrentTime::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, CallFunc_Conv_StringToText_ReturnValue_1) == 0x000060, "Member 'WBP_DebugStats_C_GetText_CurrentTime::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, K2Node_MakeStruct_FormatArgumentData) == 0x000078, "Member 'WBP_DebugStats_C_GetText_CurrentTime::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, K2Node_MakeStruct_FormatArgumentData_1) == 0x0000B8, "Member 'WBP_DebugStats_C_GetText_CurrentTime::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, CallFunc_Conv_StringToText_ReturnValue_2) == 0x0000F8, "Member 'WBP_DebugStats_C_GetText_CurrentTime::CallFunc_Conv_StringToText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, K2Node_MakeStruct_FormatArgumentData_2) == 0x000110, "Member 'WBP_DebugStats_C_GetText_CurrentTime::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, K2Node_MakeArray_Array) == 0x000150, "Member 'WBP_DebugStats_C_GetText_CurrentTime::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetText_CurrentTime, CallFunc_Format_ReturnValue) == 0x000160, "Member 'WBP_DebugStats_C_GetText_CurrentTime::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetCurrentTime
// 0x0110 (0x0110 - 0x0000)
struct WBP_DebugStats_C_GetCurrentTime final
{
public:
	class FString                                 Hour;                                              // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Minute;                                            // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Second;                                            // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_2;                              // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33[0x5];                                       // 0x0033(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDateTime                              CallFunc_Now_ReturnValue;                          // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Year;                       // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Month;                      // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Day;                        // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Hour;                       // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Minute;                     // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Second;                     // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakDateTime_Millisecond;                // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_1;           // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0080(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0090(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Len_ReturnValue;                          // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Len_ReturnValue_1;                        // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_1;          // 0x00A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_AA[0x6];                                       // 0x00AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default;                             // 0x00B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Select_Default_1;                           // 0x00C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_2;           // 0x00D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Len_ReturnValue_2;                        // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E4[0x4];                                       // 0x00E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_2;              // 0x00E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_2;          // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F9[0x7];                                       // 0x00F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default_2;                           // 0x0100(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_DebugStats_C_GetCurrentTime) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetCurrentTime");
static_assert(sizeof(WBP_DebugStats_C_GetCurrentTime) == 0x000110, "Wrong size on WBP_DebugStats_C_GetCurrentTime");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, Hour) == 0x000000, "Member 'WBP_DebugStats_C_GetCurrentTime::Hour' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, Minute) == 0x000010, "Member 'WBP_DebugStats_C_GetCurrentTime::Minute' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, Second) == 0x000020, "Member 'WBP_DebugStats_C_GetCurrentTime::Second' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, Temp_bool_Variable) == 0x000030, "Member 'WBP_DebugStats_C_GetCurrentTime::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, Temp_bool_Variable_1) == 0x000031, "Member 'WBP_DebugStats_C_GetCurrentTime::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, Temp_bool_Variable_2) == 0x000032, "Member 'WBP_DebugStats_C_GetCurrentTime::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_Now_ReturnValue) == 0x000038, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_Now_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_BreakDateTime_Year) == 0x000040, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_BreakDateTime_Year' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_BreakDateTime_Month) == 0x000044, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_BreakDateTime_Month' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_BreakDateTime_Day) == 0x000048, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_BreakDateTime_Day' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_BreakDateTime_Hour) == 0x00004C, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_BreakDateTime_Hour' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_BreakDateTime_Minute) == 0x000050, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_BreakDateTime_Minute' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_BreakDateTime_Second) == 0x000054, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_BreakDateTime_Second' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_BreakDateTime_Millisecond) == 0x000058, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_BreakDateTime_Millisecond' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_Conv_IntToString_ReturnValue) == 0x000060, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_Conv_IntToString_ReturnValue_1) == 0x000070, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_Conv_IntToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_Concat_StrStr_ReturnValue) == 0x000080, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000090, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_Len_ReturnValue) == 0x0000A0, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_Len_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_Len_ReturnValue_1) == 0x0000A4, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_Len_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x0000A8, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_EqualEqual_IntInt_ReturnValue_1) == 0x0000A9, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_EqualEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, K2Node_Select_Default) == 0x0000B0, "Member 'WBP_DebugStats_C_GetCurrentTime::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, K2Node_Select_Default_1) == 0x0000C0, "Member 'WBP_DebugStats_C_GetCurrentTime::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_Conv_IntToString_ReturnValue_2) == 0x0000D0, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_Conv_IntToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_Len_ReturnValue_2) == 0x0000E0, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_Len_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_Concat_StrStr_ReturnValue_2) == 0x0000E8, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_Concat_StrStr_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, CallFunc_EqualEqual_IntInt_ReturnValue_2) == 0x0000F8, "Member 'WBP_DebugStats_C_GetCurrentTime::CallFunc_EqualEqual_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetCurrentTime, K2Node_Select_Default_2) == 0x000100, "Member 'WBP_DebugStats_C_GetCurrentTime::K2Node_Select_Default_2' has a wrong offset!");

// Function WBP_DebugStats.WBP_DebugStats_C.GetRichText_FormatPositiveNegativeValue
// 0x0130 (0x0130 - 0x0000)
struct WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue final
{
public:
	float                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Maximum_Fractional_Digits;                         // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   ReturnValue;                                       // 0x0008(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          Temp_bool_Variable;                                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_FloatToText_ReturnValue;             // 0x0028(0x0018)()
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0048(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0088(0x0010)(ReferenceParm)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0098(0x0040)(HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00D8(0x0018)()
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x00F0(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x0100(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x0118(0x0018)()
};
static_assert(alignof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue) == 0x000008, "Wrong alignment on WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue");
static_assert(sizeof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue) == 0x000130, "Wrong size on WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, Value) == 0x000000, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::Value' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, Maximum_Fractional_Digits) == 0x000004, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::Maximum_Fractional_Digits' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, ReturnValue) == 0x000008, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, Temp_bool_Variable) == 0x000020, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, CallFunc_Conv_FloatToText_ReturnValue) == 0x000028, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::CallFunc_Conv_FloatToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x000040, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, K2Node_MakeStruct_FormatArgumentData) == 0x000048, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, K2Node_MakeArray_Array) == 0x000088, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, K2Node_MakeStruct_FormatArgumentData_1) == 0x000098, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, CallFunc_Format_ReturnValue) == 0x0000D8, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, K2Node_MakeArray_Array_1) == 0x0000F0, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, CallFunc_Format_ReturnValue_1) == 0x000100, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue, K2Node_Select_Default) == 0x000118, "Member 'WBP_DebugStats_C_GetRichText_FormatPositiveNegativeValue::K2Node_Select_Default' has a wrong offset!");

}

